# Generated by Django 2.2.12 on 2020-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv_education_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
