# Generated by Django 2.2.12 on 2020-05-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200520_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='phone',
        ),
    ]
