# Generated by Django 2.2.12 on 2020-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200520_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(default='', max_length=10),
        ),
    ]
