# Generated by Django 2.2.12 on 2020-05-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200521_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(default='', max_length=200),
        ),
    ]
