# Generated by Django 2.2.12 on 2020-05-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200521_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
