# Generated by Django 2.2.12 on 2020-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200521_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='dob',
            field=models.CharField(default='21/03/1999', max_length=200),
        ),
    ]
